### ISSUE TITLE
Adjust diagrams for dark theme 

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/docs#308]
Go through all diagrams and check that they are readable in the dark theme:
- [x] for SVG images drawn with drawio.com, reexport them with "Automatic" Appearance option and "Transparent background"
- [ ] for SVG images generated by mermaidjs, write a theme-sensitive CSS
- [x] get rid of the [enforced white background for all images](https://github.com/oasisprotocol/docs/blob/main/src/css/custom.css#L145-L148)

Transparent PNGs (do we have any?) should either be redrawn/reexported in SVG or designed in such a way that the text is readable regardless of the background. Non-transparent PNGs and JPEGs could maybe use [Docuaurus' themed images](https://docusaurus.io/docs/markdown-features/assets#themed-images) in the future?

**Comment by matevz** [comment]
Possible solution would be the following:
- for any image (png, svg, jpeg) use the default `myimage.png` filename for light themes. For dark themes, check, if `myimage_dark.png` exists and use it instead. Otherwise keep the original image. So something like the [ThemedImage](https://docusaurus.io/docs/markdown-features/assets#themed-images), but automated.
- for .svg files, instead of having another image, cool kids now detect the theme and change coloring with inline CSS. For example check out the [current favicon](https://raw.githubusercontent.com/oasisprotocol/docs/b4b701b466b310eb4fbb9a895c978c0db8cbf608/static/img/favicon.svg) or the [ROFL diagram](https://raw.githubusercontent.com/oasisprotocol/oasis-sdk/50bab3f5ab606b3d2a737579200cc3f720d83409/docs/rofl/rofl.svg).

**Comment by matevz** [comment]
drawio.com which we use for most of the hand-drawn diagrams now has theming support for SVG export. Selecting the "Automatic" theme option in the export dialog adds theme-sensitive CSS snippet in the SVG. This, and enabling transparent background gives best results in our docs.
![image](https://github.com/user-attachments/assets/b2986b7b-d3d2-498f-a39d-550a6a7a5817)

Final result:
| Light | Dark |
|---------|---------|
| ![image](https://github.com/user-attachments/assets/b878d353-eb46-4134-b088-cd92475ecb6d) | ![image](https://github.com/user-attachments/assets/1531a474-3c70-4a91-8ec3-a18d5f49017c) |

**Comment by aefhm** [comment]
## TODO

- [x] Update SVG in `oasis-sdk` https://github.com/oasisprotocol/oasis-sdk/pull/2068/
- [x] Update SVG in `sapphire-paratime` https://github.com/oasisprotocol/sapphire-paratime/pull/457
- [x] Update SVG in `oasis-core` https://github.com/oasisprotocol/oasis-core/pull/5973
- [x] Update SVG in `docs` https://github.com/oasisprotocol/docs/pull/1055
- [x] Bump dependencies

**Comment by aefhm** [comment]
Mermaid SVGs appear a little harder. Docusaurus is stripping things when I inline the SVGs.
<img width="1512" alt="Screenshot 2024-12-15 at 4 10 25 PM" src="https://github.com/user-attachments/assets/e5e367c5-ec91-4eea-aad9-34cfc8b0dde3" />

**Comment by aefhm** [comment]
Maybe we should just merge the easy changes now and give another pass later.

**Comment by matevz** [comment]
Can you open a separate issue for mermaid diagrams?

**Comment by aefhm** [comment]
> Can you open a separate issue for mermaid diagrams?

Continuing Mermaid work in https://github.com/oasisprotocol/docs/issues/1070.
